"""add_us_stock_tables

Revision ID: 2fcfa10330f0
Revises: 4c6c78c2b494
Create Date: 2025-12-07 11:47:02.168750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcfa10330f0'
down_revision: Union[str, None] = '4c6c78c2b494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # US Stock 관련 테이블만 생성 (기존 테이블들은 이미 초기 마이그레이션에서 생성됨)
    op.create_table('us_stock',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_us_stock_cik'), 'us_stock', ['cik'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_us_stock_id'), 'us_stock', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_us_stock_ticker'), 'us_stock', ['ticker'], unique=True, schema='finance')
    op.create_table('us_fundamental',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ps_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_growth', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('revenue_growth', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('beta', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['finance.us_stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'as_of_date', name='uq_us_fundamental_stock_date'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_us_fundamental_as_of_date'), 'us_fundamental', ['as_of_date'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_us_fundamental_id'), 'us_fundamental', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_us_fundamental_stock_id'), 'us_fundamental', ['stock_id'], unique=False, schema='finance')
    op.create_table('us_price_daily',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['finance.us_stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_us_price_daily_stock_date'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_us_price_daily_date'), 'us_price_daily', ['date'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_us_price_daily_id'), 'us_price_daily', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_us_price_daily_stock_id'), 'us_price_daily', ['stock_id'], unique=False, schema='finance')
    op.create_table('us_sec_filing',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_xbrl', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['finance.us_stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_us_sec_filing_filing_date'), 'us_sec_filing', ['filing_date'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_us_sec_filing_form_type'), 'us_sec_filing', ['form_type'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_us_sec_filing_id'), 'us_sec_filing', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_us_sec_filing_stock_id'), 'us_sec_filing', ['stock_id'], unique=False, schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # US Stock 관련 테이블만 삭제 (기존 테이블들은 유지)
    op.drop_index(op.f('ix_finance_us_sec_filing_stock_id'), table_name='us_sec_filing', schema='finance')
    op.drop_index(op.f('ix_finance_us_sec_filing_id'), table_name='us_sec_filing', schema='finance')
    op.drop_index(op.f('ix_finance_us_sec_filing_form_type'), table_name='us_sec_filing', schema='finance')
    op.drop_index(op.f('ix_finance_us_sec_filing_filing_date'), table_name='us_sec_filing', schema='finance')
    op.drop_table('us_sec_filing', schema='finance')
    op.drop_index(op.f('ix_finance_us_price_daily_stock_id'), table_name='us_price_daily', schema='finance')
    op.drop_index(op.f('ix_finance_us_price_daily_id'), table_name='us_price_daily', schema='finance')
    op.drop_index(op.f('ix_finance_us_price_daily_date'), table_name='us_price_daily', schema='finance')
    op.drop_table('us_price_daily', schema='finance')
    op.drop_index(op.f('ix_finance_us_fundamental_stock_id'), table_name='us_fundamental', schema='finance')
    op.drop_index(op.f('ix_finance_us_fundamental_id'), table_name='us_fundamental', schema='finance')
    op.drop_index(op.f('ix_finance_us_fundamental_as_of_date'), table_name='us_fundamental', schema='finance')
    op.drop_table('us_fundamental', schema='finance')
    op.drop_index(op.f('ix_finance_us_stock_ticker'), table_name='us_stock', schema='finance')
    op.drop_index(op.f('ix_finance_us_stock_id'), table_name='us_stock', schema='finance')
    op.drop_index(op.f('ix_finance_us_stock_cik'), table_name='us_stock', schema='finance')
    op.drop_table('us_stock', schema='finance')
    # ### end Alembic commands ###
