"""Initial migration

Revision ID: 4c6c78c2b494
Revises: 
Create Date: 2025-11-07 13:15:18.593242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6c78c2b494'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create finance schema first
    op.execute('CREATE SCHEMA IF NOT EXISTS finance')
    
    op.create_table('email_verifications',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_id'), 'email_verifications', ['id'], unique=False)
    op.create_table('financial_account',
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_financial_account_id'), 'financial_account', ['id'], unique=False, schema='finance')
    op.create_table('stock',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('isin_code', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_stock_id'), 'stock', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_stock_ticker'), 'stock', ['ticker'], unique=True, schema='finance')
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('marketing_agreed', sa.Boolean(), nullable=False),
    sa.Column('marketing_agreed_at', sa.DateTime(), nullable=True),
    sa.Column('terms_agreed', sa.Boolean(), nullable=False),
    sa.Column('terms_agreed_at', sa.DateTime(), nullable=True),
    sa.Column('privacy_agreed', sa.Boolean(), nullable=False),
    sa.Column('privacy_agreed_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'PREMIUM', name='roleenum'), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_expires_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_type', sa.Enum('FREE', 'BASIC', 'PRO', 'ENTERPRISE', name='subscriptiontypeenum'), nullable=False),
    sa.Column('subscription_started_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_auto_renew', sa.Boolean(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('financial_statement_raw',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance.financial_account.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['finance.stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_financial_statement_raw_id'), 'financial_statement_raw', ['id'], unique=False, schema='finance')
    op.create_table('lotto_numbers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('numbers', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('date_key', sa.String(length=10), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotto_numbers_id'), 'lotto_numbers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lotto_numbers_id'), table_name='lotto_numbers')
    op.drop_table('lotto_numbers')
    op.drop_index(op.f('ix_finance_financial_statement_raw_id'), table_name='financial_statement_raw', schema='finance')
    op.drop_table('financial_statement_raw', schema='finance')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_finance_stock_ticker'), table_name='stock', schema='finance')
    op.drop_index(op.f('ix_finance_stock_id'), table_name='stock', schema='finance')
    op.drop_table('stock', schema='finance')
    op.drop_index(op.f('ix_finance_financial_account_id'), table_name='financial_account', schema='finance')
    op.drop_table('financial_account', schema='finance')
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # Drop finance schema
    op.execute('DROP SCHEMA IF EXISTS finance CASCADE')
    # ### end Alembic commands ###
